# This is a basic workflow to help you get started with Actions

name: Build LogSpout

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ toky-first ]
  pull_request:
    branches: [ toky-main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKERU: ${{ secrets.DOCKERU }}
        DOCKERP: ${{ secrets.DOCKERP }}
      run: |
        docker login -u $DOCKERU -p $DOCKERP
    
    #Read version file and build
    - name: Build Image
      run: |
        export MYVERSION=`cat ./VERSION`
        docker build -t tokynet/logspout-gelf:${MYVERSION} . 
        docker push tokynet/logspout-gelf:${MYVERSION}

    #Read version file and push image
    - name: Push Image
      run: |
        export MYVERSION=`cat ./VERSION`
        docker push tokynet/logspout-gelf:${MYVERSION}
